---
title: "Extracting Random Effects"
author: "Michael Clark"
date: <span style="font-style:normal;font-family:'Open Sans'">`r Sys.Date()`</span>
output:
  html_vignette:
    toc: true
    toc_depth: 3
    df_print: kable
vignette: >
  %\VignetteIndexEntry{Extracting Random Effects}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(
  echo = T,
  message = F,
  warning = F,
  error = F,
  collapse = TRUE,
  comment = NA,
  R.options = list(width = 220),
  dev.args = list(bg = 'transparent'),
  dev = 'png',
  fig.align = 'center',
  out.width = '75%',
  fig.asp = .75,
  cache.rebuild = F,
  cache = F
)
```


```{r loadbayes, echo=FALSE}
brms_model <- mixedup:::brms_model
rstanarm_model <- mixedup:::rstanarm_model
```


## Intro

This creates a table of random effects, including the uncertainty in the estimate where applicable. 

## Examples

```{r mods}
library(lme4)
library(glmmTMB)
library(nlme)
library(brms)
library(rstanarm)
library(mgcv)


lmer_model <-
  lmer(Reaction ~ Days + (1 + Days | Subject), data = sleepstudy)

lme_model  <-
  lme(Reaction ~ Days, random = ~ 1 + Days | Subject, data = sleepstudy)

tmb_model  <-
  glmmTMB(Reaction ~ Days + (1 + Days | Subject), data = sleepstudy)

# brms_model <-
#   brm(Reaction ~ Days + (1 + Days | Subject), 
#       data = sleepstudy,
#       cores = 4,
#       refresh = -1,
#       verbose = FALSE
#   )

# rstanarm_model <-
#   stan_glmer(Reaction ~ Days + (1 + Days | Subject), 
#       data = sleepstudy,
#       cores = 4,
#       refresh = -1,
#       verbose = FALSE
#   )

# this is akin to (1 | Subject) + (0 + Days | Subject) in lme4
mgcv_model <-
  gam(
    Reaction ~  Days +
      s(Subject, bs = 're') +
      s(Days, Subject, bs = 're'),
    data = lme4::sleepstudy,
    method = 'REML'
  )
```


```{r results}
library(mixedup)

extract_random_effects(lmer_model)


extract_random_effects(lme_model)


extract_random_effects(tmb_model)


extract_random_effects(brms_model)


extract_random_effects(rstanarm_model)


extract_random_effects(mgcv_model)
```

## Options

```{r options}
lmer_model <-
  lmer(y ~ service + (1 | d) + (1 | s), data = InstEval[1:5000,])

extract_random_effects(
  lmer_model,
  ci_level = .9,
  digits = 2
)
```

```{r tmb_zip}
tmb_zip <- glmmTMB(
  count ~ spp + mined + (1 | site),
  zi =  ~ spp + mined + (1 | site),
  family = truncated_poisson,
  data = Salamanders
)

extract_random_effects(
  tmb_zip,
  cond = 'zi'
)
```

